import { Inter } from 'next/font/google'
import './globals.css'
import { Poppins } from 'next/font/google'
import Header from '../../ui/header'
import Footer from '../../ui/footer'


const poppins = Poppins({ 
    weight: ['100','200','300','400','500','600', '700', '800', '900'],
    subsets: ['latin'] 
})


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html  lang="en">
      <body className={`${poppins.className} h-screen bg-gradient-to-bl from-cyan-50 via-sky-100 to-primary-300 `}>
        <Header />
        <div>{children}</div>
        <Footer />
        </body>
    </html>
  )
}
